wandb_version: 1

epochs:
  desc: null
  value: 50
optimizer:
  desc: null
  value: Adam
batch_size:
  desc: null
  value: 64
embeddings_dim:
  desc: null
  value: 300
drop_out:
  desc: null
  value: 0.8
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693585157.80917
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.9
      8:
      - 1
      - 5
